### ISSUE TITLE
Call to "Update-MSGraphEnvironment -SchemaVersion 'beta'" fails

### ISSUE THREAD

**Issue by StevieLamb** [petripaavola/Get-IntuneManagementExtensionDiagnostics#2]
Although I have the Microsoft.Graph.Intune module installed in the CurrentUser location as the hint suggests, I'm getting the below error.

Here's a snip of the console cmds & output:

.\currentDir\  Wednesday 21 June 2023 20:35:57
00:00:32.3402543 > Install-Module -Name Microsoft.Graph.Intune -Scope CurrentUser

.\currentDir\  Wednesday 21 June 2023 20:37:17
> C:\Users\<userprofile>\Documents\PowerShell\Scripts\Get-IntuneManagementExtensionDiagnostics.ps1 -Online -ShowLogViewerUI -ConvertAllKnownGuidsToClearText

Get-IntuneManagementExtensionDiagnostics.ps1 v1.1
Author: Petri.Paavola@yodamiitti.fi / Microsoft MVP - Windows and Devices for IT

Starting Get-IntuneManagementExtensionDiagnostics

Connecting to Intune using Powershell Intune-Module
Update-MSGraphEnvironment: C:\Users\<userprofile>\Documents\PowerShell\Scripts\Get-IntuneManagementExtensionDiagnostics.ps1:618
Line |
 618 |          Update-MSGraphEnvironment -SchemaVersion 'beta'
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Update-MSGraphEnvironment' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.
Failed to update MSGraph Environment schema to Beta!

Make sure you have installed Intune Powershell module

You can install Intune module to your user account with command:
Install-Module -Name Microsoft.Graph.Intune -Scope CurrentUser

or you can install machine-wide Intune module with command:
Install-Module -Name Microsoft.Graph.Intune
More information: https://github.com/microsoft/Intune-PowerShell-SDK

My environment:
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Let me know if more infor/context is needed - or if this was designed for Windows PowerShell (v5.x)

**Comment by StevieLamb** [comment]
Just a brief update:
I repeated the process with PowerShell v5.x and everything worked.
So I suspect either the script or a dependency isn't quite happy with PowerShell v7

**Comment by petripaavola** [comment]
Script was just today updated to use Microsoft Graph module Microsoft.Graph.Authentication.

So now script should also work with Powershell 7
