### ISSUE TITLE
These lines were detected not to have right syntax so they were dropped

### ISSUE THREAD

**Issue by ncheymol** [petripaavola/Get-IntuneManagementExtensionDiagnostics#3]
Great script, thank you. I just wanted to let you know some lines of AgentExecutor.log are not parsed correctly on different devices joined to different tenants:

Computer 1, tenant 1
AgentExecutor.log Line 2520 23" component="AgentExecutor" context="" type="1" thread="1" file="">

Computer 2, tenant 1
AgentExecutor.log Line 1907 omponent="AgentExecutor" context="" type="1" thread="1" file="">
AgentExecutor.log Line 2281 e="1" thread="1" file="">
AgentExecutor.log Line 2644 824" date="8-9-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
AgentExecutor.log Line 2824 " type="1" thread="1" file="">

Computer 3, tenant 2
AgentExecutor-20230810-125736.log Line 1141 "AgentExecutor" context="" type="1" thread="1" file="">
AgentExecutor-20230802-012228.log Line 904 3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
AgentExecutor-20230802-012228.log Line 1015 <time="14:25:42.7100219" date="7-23-2023" component="AgentExecutor" context="" type="1" thread="1" file="">

**Comment by petripaavola** [comment]
Those lines are "corrupted" log entries so there is no clear start and/or end tag for log entry so script skips those lines.

But script also shows those lines in console just in case there is important information in skipped lines.

For now these are rare cases so no fix is coming soon to these skipped lines.
