### ISSUE TITLE
Win32app logs moved in Microsoft Intune 2408, AppWorkload.log

### ISSUE THREAD

**Issue by adannevig** [petripaavola/Get-IntuneManagementExtensionDiagnostics#9]
After the 2408 update Get-IntuneManagementExtensionDiagnostics will not display win32 installs because they are placed in a new logfile.

**Comment by petripaavola** [comment]
Noted! I actually checked new log file earlier but didn't go in the end and verify if log entries were echoed to new log or moved totally to new log as now has happened.

I have fixed version in testing and I'll update the fix ASAP to PowerShellGallery after testing everything works with changes.

**Comment by adannevig** [comment]
Wonderful! Thank you! :)

**Comment by petripaavola** [comment]
I uploaded fixed version to GitHub and to PowershellGallery.

**Comment by adannevig** [comment]
Fantastic! Thank you! :D
